# Generated by Django 5.1.4 on 2025-01-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(upload_to='blogs')),
                ('detail_image_1', models.ImageField(upload_to='blogs')),
                ('detail_image_2', models.ImageField(upload_to='blogs')),
            ],
        ),
    ]
