# Generated by Django 5.1.4 on 2025-01-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.CharField(default='min-mun=10.00', max_length=100)),
                ('image', models.ImageField(upload_to='shop')),
            ],
            options={
                'db_table': 'shop_blog',
            },
        ),
    ]
