# Generated by Django 5.1.4 on 2025-01-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='shopmodels',
            name='image',
        ),
        migrations.AddField(
            model_name='shopmodels',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shopmodels',
            name='images',
            field=models.ImageField(default=2, upload_to='shop_products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopmodels',
            name='is_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopmodels',
            name='long_description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopmodels',
            name='short_description',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopmodels',
            name='sku',
            field=models.CharField(default=212, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopmodels',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shop.productcategorymodel'),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.shopmodels')),
            ],
        ),
    ]
